// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_integrators.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createApiIntegrator = `-- name: CreateApiIntegrator :one
INSERT INTO api_integrators (id, name, api_key_hash, api_secret_hash, is_sandbox)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, api_key_hash, api_secret_hash, is_sandbox, created_at, updated_at
`

type CreateApiIntegratorParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	ApiKeyHash    string    `json:"api_key_hash"`
	ApiSecretHash string    `json:"api_secret_hash"`
	IsSandbox     bool      `json:"is_sandbox"`
}

func (q *Queries) CreateApiIntegrator(ctx context.Context, arg CreateApiIntegratorParams) (ApiIntegrator, error) {
	row := q.db.QueryRow(ctx, createApiIntegrator,
		arg.ID,
		arg.Name,
		arg.ApiKeyHash,
		arg.ApiSecretHash,
		arg.IsSandbox,
	)
	var i ApiIntegrator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.ApiSecretHash,
		&i.IsSandbox,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApiIntegratorByKeyHash = `-- name: GetApiIntegratorByKeyHash :one
SELECT id, name, api_key_hash, api_secret_hash, is_sandbox, created_at, updated_at FROM api_integrators
WHERE api_key_hash = $1
`

func (q *Queries) GetApiIntegratorByKeyHash(ctx context.Context, apiKeyHash string) (ApiIntegrator, error) {
	row := q.db.QueryRow(ctx, getApiIntegratorByKeyHash, apiKeyHash)
	var i ApiIntegrator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.ApiSecretHash,
		&i.IsSandbox,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
