// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: virtual_accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVirtualAccount = `-- name: CreateVirtualAccount :one
INSERT INTO virtual_accounts (id, identity_id, nomba_account_ref, account_number, bank_name, account_name, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, identity_id, nomba_account_ref, account_number, bank_name, account_name, is_active, created_at, updated_at
`

type CreateVirtualAccountParams struct {
	ID              uuid.UUID   `json:"id"`
	IdentityID      uuid.UUID   `json:"identity_id"`
	NombaAccountRef string      `json:"nomba_account_ref"`
	AccountNumber   pgtype.Text `json:"account_number"`
	BankName        pgtype.Text `json:"bank_name"`
	AccountName     pgtype.Text `json:"account_name"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) CreateVirtualAccount(ctx context.Context, arg CreateVirtualAccountParams) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, createVirtualAccount,
		arg.ID,
		arg.IdentityID,
		arg.NombaAccountRef,
		arg.AccountNumber,
		arg.BankName,
		arg.AccountName,
		arg.IsActive,
	)
	var i VirtualAccount
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.NombaAccountRef,
		&i.AccountNumber,
		&i.BankName,
		&i.AccountName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVirtualAccount = `-- name: DeactivateVirtualAccount :exec
UPDATE virtual_accounts
SET is_active = false,
    updated_at = now()
WHERE identity_id = $1 AND is_active = true
`

// Sets is_active to false when a new account is provisioned for the identity
func (q *Queries) DeactivateVirtualAccount(ctx context.Context, identityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateVirtualAccount, identityID)
	return err
}

const getActiveVirtualAccountByIdentityID = `-- name: GetActiveVirtualAccountByIdentityID :one
SELECT id, identity_id, nomba_account_ref, account_number, bank_name, account_name, is_active, created_at, updated_at FROM virtual_accounts
WHERE identity_id = $1 AND is_active = true
`

func (q *Queries) GetActiveVirtualAccountByIdentityID(ctx context.Context, identityID uuid.UUID) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, getActiveVirtualAccountByIdentityID, identityID)
	var i VirtualAccount
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.NombaAccountRef,
		&i.AccountNumber,
		&i.BankName,
		&i.AccountName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVirtualAccountByAccountNumber = `-- name: GetVirtualAccountByAccountNumber :one
SELECT id, identity_id, nomba_account_ref, account_number, bank_name, account_name, is_active, created_at, updated_at FROM virtual_accounts
WHERE account_number = $1
`

func (q *Queries) GetVirtualAccountByAccountNumber(ctx context.Context, accountNumber pgtype.Text) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, getVirtualAccountByAccountNumber, accountNumber)
	var i VirtualAccount
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.NombaAccountRef,
		&i.AccountNumber,
		&i.BankName,
		&i.AccountName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVirtualAccountByID = `-- name: GetVirtualAccountByID :one
SELECT id, identity_id, nomba_account_ref, account_number, bank_name, account_name, is_active, created_at, updated_at FROM virtual_accounts
WHERE id = $1
`

func (q *Queries) GetVirtualAccountByID(ctx context.Context, id uuid.UUID) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, getVirtualAccountByID, id)
	var i VirtualAccount
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.NombaAccountRef,
		&i.AccountNumber,
		&i.BankName,
		&i.AccountName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVirtualAccountProvisioning = `-- name: UpdateVirtualAccountProvisioning :one
UPDATE virtual_accounts
SET account_number = $2,
    bank_name = $3,
    account_name = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, identity_id, nomba_account_ref, account_number, bank_name, account_name, is_active, created_at, updated_at
`

type UpdateVirtualAccountProvisioningParams struct {
	ID            uuid.UUID   `json:"id"`
	AccountNumber pgtype.Text `json:"account_number"`
	BankName      pgtype.Text `json:"bank_name"`
	AccountName   pgtype.Text `json:"account_name"`
}

// Called after a successful provisioning to set the account number and bank info
func (q *Queries) UpdateVirtualAccountProvisioning(ctx context.Context, arg UpdateVirtualAccountProvisioningParams) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, updateVirtualAccountProvisioning,
		arg.ID,
		arg.AccountNumber,
		arg.BankName,
		arg.AccountName,
	)
	var i VirtualAccount
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.NombaAccountRef,
		&i.AccountNumber,
		&i.BankName,
		&i.AccountName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
