// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countVirtualAccountsByIntegrator = `-- name: CountVirtualAccountsByIntegrator :one
SELECT COUNT(*)
FROM virtual_accounts va
JOIN identities i ON va.identity_id = i.id
WHERE i.integrator_id = $1
`

func (q *Queries) CountVirtualAccountsByIntegrator(ctx context.Context, integratorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVirtualAccountsByIntegrator, integratorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequestLog = `-- name: CreateRequestLog :one
INSERT INTO request_logs (
    integrator_id, method, path, status_code, latency_ms, request_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, integrator_id, method, path, status_code, latency_ms, request_id, created_at
`

type CreateRequestLogParams struct {
	IntegratorID uuid.UUID `json:"integrator_id"`
	Method       string    `json:"method"`
	Path         string    `json:"path"`
	StatusCode   int32     `json:"status_code"`
	LatencyMs    int32     `json:"latency_ms"`
	RequestID    string    `json:"request_id"`
}

func (q *Queries) CreateRequestLog(ctx context.Context, arg CreateRequestLogParams) (RequestLog, error) {
	row := q.db.QueryRow(ctx, createRequestLog,
		arg.IntegratorID,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.LatencyMs,
		arg.RequestID,
	)
	var i RequestLog
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.LatencyMs,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const getErrorRate = `-- name: GetErrorRate :one
SELECT 
    COALESCE(
        (COUNT(CASE WHEN status_code >= 500 THEN 1 END)::FLOAT / NULLIF(COUNT(*), 0)) * 100, 
        0
    )::FLOAT AS error_rate
FROM request_logs
WHERE integrator_id = $1 
  AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) GetErrorRate(ctx context.Context, integratorID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getErrorRate, integratorID)
	var error_rate float64
	err := row.Scan(&error_rate)
	return error_rate, err
}

const getP99Latency = `-- name: GetP99Latency :one
SELECT 
    COALESCE(
        percentile_cont(0.99) WITHIN GROUP (ORDER BY latency_ms), 
        0
    )::FLOAT AS p99_latency
FROM request_logs
WHERE integrator_id = $1 
  AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) GetP99Latency(ctx context.Context, integratorID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getP99Latency, integratorID)
	var p99_latency float64
	err := row.Scan(&p99_latency)
	return p99_latency, err
}

const getRecentRequestLogs = `-- name: GetRecentRequestLogs :many
SELECT id, integrator_id, method, path, status_code, latency_ms, request_id, created_at
FROM request_logs
WHERE integrator_id = $1
ORDER BY created_at DESC
LIMIT 5
`

func (q *Queries) GetRecentRequestLogs(ctx context.Context, integratorID uuid.UUID) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, getRecentRequestLogs, integratorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestLog{}
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.LatencyMs,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalApiRequests = `-- name: GetTotalApiRequests :one
SELECT COUNT(*)
FROM request_logs
WHERE integrator_id = $1
  AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) GetTotalApiRequests(ctx context.Context, integratorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalApiRequests, integratorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
