// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const generateInvoicesForPeriod = `-- name: GenerateInvoicesForPeriod :exec
INSERT INTO console.invoices (
	integrator_id, billing_record_id, period, amount_kobo, status
)
SELECT 
	integrator_id, id, console.billing_records.period, amount_due_kobo, 'open'
FROM console.billing_records
WHERE console.billing_records.period = $1 AND console.billing_records.environment = 'production' AND amount_due_kobo > 0
ON CONFLICT DO NOTHING
`

func (q *Queries) GenerateInvoicesForPeriod(ctx context.Context, period string) error {
	_, err := q.db.Exec(ctx, generateInvoicesForPeriod, period)
	return err
}

const getBillingRecords = `-- name: GetBillingRecords :many
SELECT id, integrator_id, environment, period, accounts_provisioned, transactions_processed, webhook_deliveries, amount_due_kobo, adjustment_kobo, adjustment_reason, synced_at FROM console.billing_records
WHERE integrator_id = $1
ORDER BY synced_at DESC
`

func (q *Queries) GetBillingRecords(ctx context.Context, integratorID uuid.UUID) ([]ConsoleBillingRecord, error) {
	rows, err := q.db.Query(ctx, getBillingRecords, integratorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsoleBillingRecord{}
	for rows.Next() {
		var i ConsoleBillingRecord
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.Environment,
			&i.Period,
			&i.AccountsProvisioned,
			&i.TransactionsProcessed,
			&i.WebhookDeliveries,
			&i.AmountDueKobo,
			&i.AdjustmentKobo,
			&i.AdjustmentReason,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultPaymentMethod = `-- name: GetDefaultPaymentMethod :one
SELECT id, integrator_id, nomba_token_key, card_last4, card_brand, is_default, created_at FROM console.payment_methods
WHERE integrator_id = $1 AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetDefaultPaymentMethod(ctx context.Context, integratorID uuid.UUID) (ConsolePaymentMethod, error) {
	row := q.db.QueryRow(ctx, getDefaultPaymentMethod, integratorID)
	var i ConsolePaymentMethod
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.NombaTokenKey,
		&i.CardLast4,
		&i.CardBrand,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByVirtualAccountID = `-- name: GetIdentityByVirtualAccountID :one
SELECT i.id, i.integrator_id, i.external_reference, i.display_name, i.state, i.failure_reason, i.metadata, i.created_at, i.updated_at, c.environment as credential_environment
FROM public.identities i
JOIN public.virtual_accounts v ON i.id = v.identity_id
JOIN public.api_credentials c ON i.integrator_id = c.integrator_id
WHERE v.id = $1
LIMIT 1
`

type GetIdentityByVirtualAccountIDRow struct {
	ID                    uuid.UUID       `json:"id"`
	IntegratorID          uuid.UUID       `json:"integrator_id"`
	ExternalReference     string          `json:"external_reference"`
	DisplayName           string          `json:"display_name"`
	State                 string          `json:"state"`
	FailureReason         pgtype.Text     `json:"failure_reason"`
	Metadata              json.RawMessage `json:"metadata"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
	CredentialEnvironment string          `json:"credential_environment"`
}

func (q *Queries) GetIdentityByVirtualAccountID(ctx context.Context, id uuid.UUID) (GetIdentityByVirtualAccountIDRow, error) {
	row := q.db.QueryRow(ctx, getIdentityByVirtualAccountID, id)
	var i GetIdentityByVirtualAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.ExternalReference,
		&i.DisplayName,
		&i.State,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialEnvironment,
	)
	return i, err
}

const getIntegratorInvoices = `-- name: GetIntegratorInvoices :many
SELECT id, integrator_id, billing_record_id, period, amount_kobo, status, nomba_order_ref, paid_at, retry_count, next_retry_at, created_at FROM console.invoices
WHERE integrator_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetIntegratorInvoices(ctx context.Context, integratorID uuid.UUID) ([]ConsoleInvoice, error) {
	rows, err := q.db.Query(ctx, getIntegratorInvoices, integratorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsoleInvoice{}
	for rows.Next() {
		var i ConsoleInvoice
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.BillingRecordID,
			&i.Period,
			&i.AmountKobo,
			&i.Status,
			&i.NombaOrderRef,
			&i.PaidAt,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIntegratorUsageEvents = `-- name: GetIntegratorUsageEvents :many
SELECT id, integrator_id, environment, event_type, reference_id, amount_kobo, occurred_at FROM console.usage_events
WHERE integrator_id = $1 AND environment = $2 AND occurred_at >= $3 AND occurred_at <= $4
ORDER BY occurred_at DESC
`

type GetIntegratorUsageEventsParams struct {
	IntegratorID uuid.UUID `json:"integrator_id"`
	Environment  string    `json:"environment"`
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) GetIntegratorUsageEvents(ctx context.Context, arg GetIntegratorUsageEventsParams) ([]ConsoleUsageEvent, error) {
	rows, err := q.db.Query(ctx, getIntegratorUsageEvents,
		arg.IntegratorID,
		arg.Environment,
		arg.OccurredAt,
		arg.OccurredAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsoleUsageEvent{}
	for rows.Next() {
		var i ConsoleUsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.Environment,
			&i.EventType,
			&i.ReferenceID,
			&i.AmountKobo,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIntegratorWalletBalance = `-- name: GetIntegratorWalletBalance :one
SELECT wallet_balance_kobo FROM public.api_integrators WHERE id = $1
`

func (q *Queries) GetIntegratorWalletBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getIntegratorWalletBalance, id)
	var wallet_balance_kobo int64
	err := row.Scan(&wallet_balance_kobo)
	return wallet_balance_kobo, err
}

const getPendingInvoices = `-- name: GetPendingInvoices :many
SELECT id, integrator_id, billing_record_id, period, amount_kobo, status, nomba_order_ref, paid_at, retry_count, next_retry_at, created_at FROM console.invoices
WHERE status = 'open' OR status = 'failed' AND retry_count < 3 AND (next_retry_at IS NULL OR next_retry_at <= now())
`

func (q *Queries) GetPendingInvoices(ctx context.Context) ([]ConsoleInvoice, error) {
	rows, err := q.db.Query(ctx, getPendingInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsoleInvoice{}
	for rows.Next() {
		var i ConsoleInvoice
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.BillingRecordID,
			&i.Period,
			&i.AmountKobo,
			&i.Status,
			&i.NombaOrderRef,
			&i.PaidAt,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInvoice = `-- name: InsertInvoice :one
INSERT INTO console.invoices (
    integrator_id, billing_record_id, period, amount_kobo, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, integrator_id, billing_record_id, period, amount_kobo, status, nomba_order_ref, paid_at, retry_count, next_retry_at, created_at
`

type InsertInvoiceParams struct {
	IntegratorID    uuid.UUID `json:"integrator_id"`
	BillingRecordID uuid.UUID `json:"billing_record_id"`
	Period          string    `json:"period"`
	AmountKobo      int64     `json:"amount_kobo"`
	Status          string    `json:"status"`
}

func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (ConsoleInvoice, error) {
	row := q.db.QueryRow(ctx, insertInvoice,
		arg.IntegratorID,
		arg.BillingRecordID,
		arg.Period,
		arg.AmountKobo,
		arg.Status,
	)
	var i ConsoleInvoice
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.BillingRecordID,
		&i.Period,
		&i.AmountKobo,
		&i.Status,
		&i.NombaOrderRef,
		&i.PaidAt,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPaymentMethod = `-- name: InsertPaymentMethod :one
INSERT INTO console.payment_methods (
    integrator_id, nomba_token_key, card_last4, card_brand, is_default
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, integrator_id, nomba_token_key, card_last4, card_brand, is_default, created_at
`

type InsertPaymentMethodParams struct {
	IntegratorID  uuid.UUID   `json:"integrator_id"`
	NombaTokenKey string      `json:"nomba_token_key"`
	CardLast4     pgtype.Text `json:"card_last4"`
	CardBrand     pgtype.Text `json:"card_brand"`
	IsDefault     bool        `json:"is_default"`
}

func (q *Queries) InsertPaymentMethod(ctx context.Context, arg InsertPaymentMethodParams) (ConsolePaymentMethod, error) {
	row := q.db.QueryRow(ctx, insertPaymentMethod,
		arg.IntegratorID,
		arg.NombaTokenKey,
		arg.CardLast4,
		arg.CardBrand,
		arg.IsDefault,
	)
	var i ConsolePaymentMethod
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.NombaTokenKey,
		&i.CardLast4,
		&i.CardBrand,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const insertUsageEvent = `-- name: InsertUsageEvent :exec
INSERT INTO console.usage_events (
    integrator_id, environment, event_type, reference_id, amount_kobo
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertUsageEventParams struct {
	IntegratorID uuid.UUID `json:"integrator_id"`
	Environment  string    `json:"environment"`
	EventType    string    `json:"event_type"`
	ReferenceID  string    `json:"reference_id"`
	AmountKobo   int64     `json:"amount_kobo"`
}

func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.Exec(ctx, insertUsageEvent,
		arg.IntegratorID,
		arg.Environment,
		arg.EventType,
		arg.ReferenceID,
		arg.AmountKobo,
	)
	return err
}

const rollupUsageEvents = `-- name: RollupUsageEvents :exec
INSERT INTO console.billing_records (
	integrator_id, environment, period,
	accounts_provisioned, transactions_processed, webhook_deliveries, amount_due_kobo
)
SELECT 
	integrator_id, environment, $1 as period,
	COUNT(CASE WHEN event_type = 'account_provisioned' THEN 1 END) as accounts_provisioned,
	COUNT(CASE WHEN event_type = 'transaction_processed' THEN 1 END) as transactions_processed,
	COUNT(CASE WHEN event_type = 'webhook_delivery' THEN 1 END) as webhook_deliveries,
	SUM(amount_kobo) as amount_due_kobo
FROM console.usage_events
WHERE to_char(occurred_at, 'YYYY-MM') = $1 AND environment = 'production'
GROUP BY integrator_id, environment
ON CONFLICT (integrator_id, period, environment) DO UPDATE SET
	accounts_provisioned = EXCLUDED.accounts_provisioned,
	transactions_processed = EXCLUDED.transactions_processed,
	webhook_deliveries = EXCLUDED.webhook_deliveries,
	amount_due_kobo = EXCLUDED.amount_due_kobo,
	synced_at = now()
`

func (q *Queries) RollupUsageEvents(ctx context.Context, period string) error {
	_, err := q.db.Exec(ctx, rollupUsageEvents, period)
	return err
}

const suspendIntegrator = `-- name: SuspendIntegrator :exec
UPDATE public.api_integrators
SET status = 'suspended'
WHERE id = $1
`

func (q *Queries) SuspendIntegrator(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, suspendIntegrator, id)
	return err
}

const unsetDefaultPaymentMethods = `-- name: UnsetDefaultPaymentMethods :exec
UPDATE console.payment_methods
SET is_default = FALSE
WHERE integrator_id = $1
`

func (q *Queries) UnsetDefaultPaymentMethods(ctx context.Context, integratorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetDefaultPaymentMethods, integratorID)
	return err
}

const updateIntegratorWalletBalance = `-- name: UpdateIntegratorWalletBalance :exec
UPDATE public.api_integrators
SET wallet_balance_kobo = wallet_balance_kobo + $2
WHERE id = $1
`

type UpdateIntegratorWalletBalanceParams struct {
	ID                uuid.UUID `json:"id"`
	WalletBalanceKobo int64     `json:"wallet_balance_kobo"`
}

func (q *Queries) UpdateIntegratorWalletBalance(ctx context.Context, arg UpdateIntegratorWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateIntegratorWalletBalance, arg.ID, arg.WalletBalanceKobo)
	return err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE console.invoices
SET status = $2, nomba_order_ref = $3, paid_at = $4, retry_count = $5, next_retry_at = $6
WHERE id = $1
`

type UpdateInvoiceStatusParams struct {
	ID            uuid.UUID          `json:"id"`
	Status        string             `json:"status"`
	NombaOrderRef pgtype.Text        `json:"nomba_order_ref"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RetryCount    int32              `json:"retry_count"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus,
		arg.ID,
		arg.Status,
		arg.NombaOrderRef,
		arg.PaidAt,
		arg.RetryCount,
		arg.NextRetryAt,
	)
	return err
}

const upsertBillingRecord = `-- name: UpsertBillingRecord :exec
INSERT INTO console.billing_records (
    integrator_id, environment, period, 
    accounts_provisioned, transactions_processed, webhook_deliveries, amount_due_kobo
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) ON CONFLICT (integrator_id, period, environment) DO UPDATE SET
    accounts_provisioned = console.billing_records.accounts_provisioned + EXCLUDED.accounts_provisioned,
    transactions_processed = console.billing_records.transactions_processed + EXCLUDED.transactions_processed,
    webhook_deliveries = console.billing_records.webhook_deliveries + EXCLUDED.webhook_deliveries,
    amount_due_kobo = console.billing_records.amount_due_kobo + EXCLUDED.amount_due_kobo,
    synced_at = now()
`

type UpsertBillingRecordParams struct {
	IntegratorID          uuid.UUID `json:"integrator_id"`
	Environment           string    `json:"environment"`
	Period                string    `json:"period"`
	AccountsProvisioned   int64     `json:"accounts_provisioned"`
	TransactionsProcessed int64     `json:"transactions_processed"`
	WebhookDeliveries     int64     `json:"webhook_deliveries"`
	AmountDueKobo         int64     `json:"amount_due_kobo"`
}

func (q *Queries) UpsertBillingRecord(ctx context.Context, arg UpsertBillingRecordParams) error {
	_, err := q.db.Exec(ctx, upsertBillingRecord,
		arg.IntegratorID,
		arg.Environment,
		arg.Period,
		arg.AccountsProvisioned,
		arg.TransactionsProcessed,
		arg.WebhookDeliveries,
		arg.AmountDueKobo,
	)
	return err
}
