// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: console_auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getConsoleSession = `-- name: GetConsoleSession :one
SELECT s.user_id, u.integrator_id, u.role
FROM console.sessions s
JOIN console.users u ON s.user_id = u.id
WHERE s.id = $1 AND s.expires_at > now() AND s.revoked_at IS NULL
`

type GetConsoleSessionRow struct {
	UserID       uuid.UUID   `json:"user_id"`
	IntegratorID pgtype.UUID `json:"integrator_id"`
	Role         interface{} `json:"role"`
}

func (q *Queries) GetConsoleSession(ctx context.Context, id string) (GetConsoleSessionRow, error) {
	row := q.db.QueryRow(ctx, getConsoleSession, id)
	var i GetConsoleSessionRow
	err := row.Scan(&i.UserID, &i.IntegratorID, &i.Role)
	return i, err
}
