// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exceptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExceptionByID = `-- name: GetExceptionByID :one
SELECT id, integrator_id, type, amount_kobo, nomba_reference, related_account_id, status, resolution_action, resolution_notes, successor_identity_id, detected_at, resolved_at, created_at FROM exceptions
WHERE id = $1 AND integrator_id = $2
`

type GetExceptionByIDParams struct {
	ID           uuid.UUID `json:"id"`
	IntegratorID uuid.UUID `json:"integrator_id"`
}

func (q *Queries) GetExceptionByID(ctx context.Context, arg GetExceptionByIDParams) (Exception, error) {
	row := q.db.QueryRow(ctx, getExceptionByID, arg.ID, arg.IntegratorID)
	var i Exception
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.Type,
		&i.AmountKobo,
		&i.NombaReference,
		&i.RelatedAccountID,
		&i.Status,
		&i.ResolutionAction,
		&i.ResolutionNotes,
		&i.SuccessorIdentityID,
		&i.DetectedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertException = `-- name: InsertException :one
INSERT INTO exceptions (id, integrator_id, type, amount_kobo, nomba_reference, related_account_id, status, detected_at)
VALUES ($1, $2, $3, $4, $5, $6, 'open', now())
RETURNING id, integrator_id, type, amount_kobo, nomba_reference, related_account_id, status, resolution_action, resolution_notes, successor_identity_id, detected_at, resolved_at, created_at
`

type InsertExceptionParams struct {
	ID               uuid.UUID   `json:"id"`
	IntegratorID     uuid.UUID   `json:"integrator_id"`
	Type             string      `json:"type"`
	AmountKobo       int64       `json:"amount_kobo"`
	NombaReference   string      `json:"nomba_reference"`
	RelatedAccountID pgtype.UUID `json:"related_account_id"`
}

func (q *Queries) InsertException(ctx context.Context, arg InsertExceptionParams) (Exception, error) {
	row := q.db.QueryRow(ctx, insertException,
		arg.ID,
		arg.IntegratorID,
		arg.Type,
		arg.AmountKobo,
		arg.NombaReference,
		arg.RelatedAccountID,
	)
	var i Exception
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.Type,
		&i.AmountKobo,
		&i.NombaReference,
		&i.RelatedAccountID,
		&i.Status,
		&i.ResolutionAction,
		&i.ResolutionNotes,
		&i.SuccessorIdentityID,
		&i.DetectedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExceptionsByStatus = `-- name: ListExceptionsByStatus :many
SELECT id, integrator_id, type, amount_kobo, nomba_reference, related_account_id, status, resolution_action, resolution_notes, successor_identity_id, detected_at, resolved_at, created_at FROM exceptions
WHERE integrator_id = $1 AND status = $2
ORDER BY detected_at DESC
LIMIT $3 OFFSET $4
`

type ListExceptionsByStatusParams struct {
	IntegratorID uuid.UUID `json:"integrator_id"`
	Status       string    `json:"status"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListExceptionsByStatus(ctx context.Context, arg ListExceptionsByStatusParams) ([]Exception, error) {
	rows, err := q.db.Query(ctx, listExceptionsByStatus,
		arg.IntegratorID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exception{}
	for rows.Next() {
		var i Exception
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.Type,
			&i.AmountKobo,
			&i.NombaReference,
			&i.RelatedAccountID,
			&i.Status,
			&i.ResolutionAction,
			&i.ResolutionNotes,
			&i.SuccessorIdentityID,
			&i.DetectedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenExceptions = `-- name: ListOpenExceptions :many
SELECT id, integrator_id, type, amount_kobo, nomba_reference, related_account_id, status, resolution_action, resolution_notes, successor_identity_id, detected_at, resolved_at, created_at FROM exceptions
WHERE integrator_id = $1 AND status = 'open'
ORDER BY detected_at ASC
LIMIT $2 OFFSET $3
`

type ListOpenExceptionsParams struct {
	IntegratorID uuid.UUID `json:"integrator_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListOpenExceptions(ctx context.Context, arg ListOpenExceptionsParams) ([]Exception, error) {
	rows, err := q.db.Query(ctx, listOpenExceptions, arg.IntegratorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exception{}
	for rows.Next() {
		var i Exception
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.Type,
			&i.AmountKobo,
			&i.NombaReference,
			&i.RelatedAccountID,
			&i.Status,
			&i.ResolutionAction,
			&i.ResolutionNotes,
			&i.SuccessorIdentityID,
			&i.DetectedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveException = `-- name: ResolveException :one
UPDATE exceptions
SET status = 'resolved',
    resolution_action = $3,
    resolution_notes = $4,
    successor_identity_id = $5,
    resolved_at = now()
WHERE id = $1 AND integrator_id = $2 AND status = 'open'
RETURNING id, integrator_id, type, amount_kobo, nomba_reference, related_account_id, status, resolution_action, resolution_notes, successor_identity_id, detected_at, resolved_at, created_at
`

type ResolveExceptionParams struct {
	ID                  uuid.UUID   `json:"id"`
	IntegratorID        uuid.UUID   `json:"integrator_id"`
	ResolutionAction    pgtype.Text `json:"resolution_action"`
	ResolutionNotes     pgtype.Text `json:"resolution_notes"`
	SuccessorIdentityID pgtype.UUID `json:"successor_identity_id"`
}

func (q *Queries) ResolveException(ctx context.Context, arg ResolveExceptionParams) (Exception, error) {
	row := q.db.QueryRow(ctx, resolveException,
		arg.ID,
		arg.IntegratorID,
		arg.ResolutionAction,
		arg.ResolutionNotes,
		arg.SuccessorIdentityID,
	)
	var i Exception
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.Type,
		&i.AmountKobo,
		&i.NombaReference,
		&i.RelatedAccountID,
		&i.Status,
		&i.ResolutionAction,
		&i.ResolutionNotes,
		&i.SuccessorIdentityID,
		&i.DetectedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}
