// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT monnify_reference, ledger_entry_id, first_seen_via, created_at FROM idempotency_keys
WHERE monnify_reference = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, monnifyReference string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, monnifyReference)
	var i IdempotencyKey
	err := row.Scan(
		&i.MonnifyReference,
		&i.LedgerEntryID,
		&i.FirstSeenVia,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (monnify_reference, ledger_entry_id, first_seen_via)
VALUES ($1, $2, $3)
RETURNING monnify_reference, ledger_entry_id, first_seen_via, created_at
`

type InsertIdempotencyKeyParams struct {
	MonnifyReference string    `json:"monnify_reference"`
	LedgerEntryID  uuid.UUID `json:"ledger_entry_id"`
	FirstSeenVia   string    `json:"first_seen_via"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey, arg.MonnifyReference, arg.LedgerEntryID, arg.FirstSeenVia)
	var i IdempotencyKey
	err := row.Scan(
		&i.MonnifyReference,
		&i.LedgerEntryID,
		&i.FirstSeenVia,
		&i.CreatedAt,
	)
	return i, err
}
