// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (id, integrator_id, external_reference, display_name, state, metadata)
VALUES ($1, $2, $3, $4, 'pending', $5)
RETURNING id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at
`

type CreateIdentityParams struct {
	ID                uuid.UUID       `json:"id"`
	IntegratorID      uuid.UUID       `json:"integrator_id"`
	ExternalReference string          `json:"external_reference"`
	DisplayName       string          `json:"display_name"`
	Metadata          json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.ID,
		arg.IntegratorID,
		arg.ExternalReference,
		arg.DisplayName,
		arg.Metadata,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.ExternalReference,
		&i.DisplayName,
		&i.State,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByExternalReference = `-- name: GetIdentityByExternalReference :one
SELECT id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at FROM identities
WHERE integrator_id = $1 AND external_reference = $2
`

type GetIdentityByExternalReferenceParams struct {
	IntegratorID      uuid.UUID `json:"integrator_id"`
	ExternalReference string    `json:"external_reference"`
}

func (q *Queries) GetIdentityByExternalReference(ctx context.Context, arg GetIdentityByExternalReferenceParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByExternalReference, arg.IntegratorID, arg.ExternalReference)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.ExternalReference,
		&i.DisplayName,
		&i.State,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at FROM identities
WHERE id = $1 AND integrator_id = $2
`

type GetIdentityByIDParams struct {
	ID           uuid.UUID `json:"id"`
	IntegratorID uuid.UUID `json:"integrator_id"`
}

func (q *Queries) GetIdentityByID(ctx context.Context, arg GetIdentityByIDParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, arg.ID, arg.IntegratorID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.ExternalReference,
		&i.DisplayName,
		&i.State,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdentityEvent = `-- name: InsertIdentityEvent :one
INSERT INTO identity_events (id, identity_id, event_type, previous_state, new_state, detail)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, identity_id, event_type, previous_state, new_state, detail, created_at
`

type InsertIdentityEventParams struct {
	ID            uuid.UUID       `json:"id"`
	IdentityID    uuid.UUID       `json:"identity_id"`
	EventType     string          `json:"event_type"`
	PreviousState pgtype.Text     `json:"previous_state"`
	NewState      pgtype.Text     `json:"new_state"`
	Detail        json.RawMessage `json:"detail"`
}

func (q *Queries) InsertIdentityEvent(ctx context.Context, arg InsertIdentityEventParams) (IdentityEvent, error) {
	row := q.db.QueryRow(ctx, insertIdentityEvent,
		arg.ID,
		arg.IdentityID,
		arg.EventType,
		arg.PreviousState,
		arg.NewState,
		arg.Detail,
	)
	var i IdentityEvent
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.EventType,
		&i.PreviousState,
		&i.NewState,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listAllIdentitiesByState = `-- name: ListAllIdentitiesByState :many
SELECT id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at FROM identities
WHERE state = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAllIdentitiesByState(ctx context.Context, state string) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listAllIdentitiesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.ExternalReference,
			&i.DisplayName,
			&i.State,
			&i.FailureReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at FROM identities
WHERE integrator_id = $1 
  AND ($4::text IS NULL OR state = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIdentitiesParams struct {
	IntegratorID uuid.UUID   `json:"integrator_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	State        pgtype.Text `json:"state"`
}

func (q *Queries) ListIdentities(ctx context.Context, arg ListIdentitiesParams) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentities,
		arg.IntegratorID,
		arg.Limit,
		arg.Offset,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.ExternalReference,
			&i.DisplayName,
			&i.State,
			&i.FailureReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByState = `-- name: ListIdentitiesByState :many
SELECT id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at FROM identities
WHERE integrator_id = $1 AND state = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListIdentitiesByStateParams struct {
	IntegratorID uuid.UUID `json:"integrator_id"`
	State        string    `json:"state"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListIdentitiesByState(ctx context.Context, arg ListIdentitiesByStateParams) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByState,
		arg.IntegratorID,
		arg.State,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.ExternalReference,
			&i.DisplayName,
			&i.State,
			&i.FailureReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityEvents = `-- name: ListIdentityEvents :many
SELECT id, identity_id, event_type, previous_state, new_state, detail, created_at FROM identity_events
WHERE identity_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListIdentityEvents(ctx context.Context, identityID uuid.UUID) ([]IdentityEvent, error) {
	rows, err := q.db.Query(ctx, listIdentityEvents, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityEvent{}
	for rows.Next() {
		var i IdentityEvent
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.EventType,
			&i.PreviousState,
			&i.NewState,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentityProfile = `-- name: UpdateIdentityProfile :one
UPDATE identities
SET display_name = COALESCE($3, display_name),
    metadata = COALESCE($4, metadata),
    updated_at = now()
WHERE id = $1 AND integrator_id = $2
RETURNING id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at
`

type UpdateIdentityProfileParams struct {
	ID           uuid.UUID   `json:"id"`
	IntegratorID uuid.UUID   `json:"integrator_id"`
	DisplayName  pgtype.Text `json:"display_name"`
	Metadata     []byte      `json:"metadata"`
}

// Used for renames and metadata updates only. Never changes state or id.
func (q *Queries) UpdateIdentityProfile(ctx context.Context, arg UpdateIdentityProfileParams) (Identity, error) {
	row := q.db.QueryRow(ctx, updateIdentityProfile,
		arg.ID,
		arg.IntegratorID,
		arg.DisplayName,
		arg.Metadata,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.ExternalReference,
		&i.DisplayName,
		&i.State,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityState = `-- name: UpdateIdentityState :one
UPDATE identities
SET state = $3,
    failure_reason = $4,
    updated_at = now()
WHERE id = $1 AND integrator_id = $2
RETURNING id, integrator_id, external_reference, display_name, state, failure_reason, metadata, created_at, updated_at
`

type UpdateIdentityStateParams struct {
	ID            uuid.UUID   `json:"id"`
	IntegratorID  uuid.UUID   `json:"integrator_id"`
	State         string      `json:"state"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

// The only query allowed to mutate `state`. Called exclusively from
// account/lifecycle.go's Transition() function, never directly from a handler
// or service method, per the package boundary rules in ARCHITECTURE.md.
func (q *Queries) UpdateIdentityState(ctx context.Context, arg UpdateIdentityStateParams) (Identity, error) {
	row := q.db.QueryRow(ctx, updateIdentityState,
		arg.ID,
		arg.IntegratorID,
		arg.State,
		arg.FailureReason,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.ExternalReference,
		&i.DisplayName,
		&i.State,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
