// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger_entries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLedgerOpeningBalance = `-- name: GetLedgerOpeningBalance :one
SELECT COALESCE(SUM(amount_kobo), 0)::BIGINT AS balance
FROM ledger_entries
WHERE identity_id = $1
  AND occurred_at < $2
  AND status = 'matched'
`

type GetLedgerOpeningBalanceParams struct {
	IdentityID uuid.UUID `json:"identity_id"`
	OccurredAt time.Time `json:"occurred_at"`
}

// Calculates the sum of all 'inbound' matched transactions before the given time
func (q *Queries) GetLedgerOpeningBalance(ctx context.Context, arg GetLedgerOpeningBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLedgerOpeningBalance, arg.IdentityID, arg.OccurredAt)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (id, virtual_account_id, identity_id, amount_kobo, direction, status, monnify_reference, source, narration, sender_name, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, virtual_account_id, identity_id, amount_kobo, direction, status, monnify_reference, source, narration, sender_name, occurred_at, created_at
`

type InsertLedgerEntryParams struct {
	ID               uuid.UUID   `json:"id"`
	VirtualAccountID uuid.UUID   `json:"virtual_account_id"`
	IdentityID       uuid.UUID   `json:"identity_id"`
	AmountKobo       int64       `json:"amount_kobo"`
	Direction        string      `json:"direction"`
	Status           string      `json:"status"`
	MonnifyReference   string      `json:"monnify_reference"`
	Source           string      `json:"source"`
	Narration        pgtype.Text `json:"narration"`
	SenderName       pgtype.Text `json:"sender_name"`
	OccurredAt       time.Time   `json:"occurred_at"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.ID,
		arg.VirtualAccountID,
		arg.IdentityID,
		arg.AmountKobo,
		arg.Direction,
		arg.Status,
		arg.MonnifyReference,
		arg.Source,
		arg.Narration,
		arg.SenderName,
		arg.OccurredAt,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.VirtualAccountID,
		&i.IdentityID,
		&i.AmountKobo,
		&i.Direction,
		&i.Status,
		&i.MonnifyReference,
		&i.Source,
		&i.Narration,
		&i.SenderName,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, virtual_account_id, identity_id, amount_kobo, direction, status, monnify_reference, source, narration, sender_name, occurred_at, created_at FROM ledger_entries
WHERE virtual_account_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	VirtualAccountID uuid.UUID `json:"virtual_account_id"`
	Limit            int32     `json:"limit"`
	Offset           int32     `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.VirtualAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.VirtualAccountID,
			&i.IdentityID,
			&i.AmountKobo,
			&i.Direction,
			&i.Status,
			&i.MonnifyReference,
			&i.Source,
			&i.Narration,
			&i.SenderName,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByIdentityAndPeriod = `-- name: ListLedgerEntriesByIdentityAndPeriod :many
SELECT id, virtual_account_id, identity_id, amount_kobo, direction, status, monnify_reference, source, narration, sender_name, occurred_at, created_at FROM ledger_entries
WHERE identity_id = $1
  AND occurred_at >= $2
  AND occurred_at < $3
ORDER BY occurred_at ASC
`

type ListLedgerEntriesByIdentityAndPeriodParams struct {
	IdentityID   uuid.UUID `json:"identity_id"`
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) ListLedgerEntriesByIdentityAndPeriod(ctx context.Context, arg ListLedgerEntriesByIdentityAndPeriodParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByIdentityAndPeriod, arg.IdentityID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.VirtualAccountID,
			&i.IdentityID,
			&i.AmountKobo,
			&i.Direction,
			&i.Status,
			&i.MonnifyReference,
			&i.Source,
			&i.Narration,
			&i.SenderName,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
