// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRequestLogs = `-- name: CountRequestLogs :one
SELECT COUNT(*)
FROM request_logs
WHERE integrator_id = $1
  AND ($2::text IS NULL OR method = $2)
  AND ($3::int IS NULL OR status_code = $3)
`

type CountRequestLogsParams struct {
	IntegratorID uuid.UUID   `json:"integrator_id"`
	Method       pgtype.Text `json:"method"`
	StatusCode   pgtype.Int4 `json:"status_code"`
}

func (q *Queries) CountRequestLogs(ctx context.Context, arg CountRequestLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestLogs, arg.IntegratorID, arg.Method, arg.StatusCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPaginatedRequestLogs = `-- name: GetPaginatedRequestLogs :many
SELECT id, integrator_id, method, path, status_code, latency_ms, request_id, created_at
FROM request_logs
WHERE integrator_id = $1
  AND ($4::text IS NULL OR method = $4)
  AND ($5::int IS NULL OR status_code = $5)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPaginatedRequestLogsParams struct {
	IntegratorID uuid.UUID   `json:"integrator_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	Method       pgtype.Text `json:"method"`
	StatusCode   pgtype.Int4 `json:"status_code"`
}

func (q *Queries) GetPaginatedRequestLogs(ctx context.Context, arg GetPaginatedRequestLogsParams) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, getPaginatedRequestLogs,
		arg.IntegratorID,
		arg.Limit,
		arg.Offset,
		arg.Method,
		arg.StatusCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestLog{}
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.LatencyMs,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
