// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiCredential struct {
	ID            uuid.UUID          `json:"id"`
	IntegratorID  uuid.UUID          `json:"integrator_id"`
	Environment   string             `json:"environment"`
	KeyID         string             `json:"key_id"`
	SecretHash    string             `json:"secret_hash"`
	Label         pgtype.Text        `json:"label"`
	CreatedAt     time.Time          `json:"created_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	RotatedAt     pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy     pgtype.UUID        `json:"revoked_by"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	AllowedIps    []string           `json:"allowed_ips"`
	Scopes        []string           `json:"scopes"`
}

type ApiIntegrator struct {
	ID                        uuid.UUID          `json:"id"`
	Name                      string             `json:"name"`
	CreatedAt                 time.Time          `json:"created_at"`
	UpdatedAt                 time.Time          `json:"updated_at"`
	Plan                      string             `json:"plan"`
	Status                    interface{}        `json:"status"`
	ProductionAccessGranted   bool               `json:"production_access_granted"`
	ProductionAccessGrantedAt pgtype.Timestamptz `json:"production_access_granted_at"`
	ProductionAccessGrantedBy pgtype.UUID        `json:"production_access_granted_by"`
	WalletBalanceKobo         int64              `json:"wallet_balance_kobo"`
}

type ConsoleAdminAuditLog struct {
	ID                 uuid.UUID       `json:"id"`
	ActorUserID        uuid.UUID       `json:"actor_user_id"`
	Action             interface{}     `json:"action"`
	TargetIntegratorID pgtype.UUID     `json:"target_integrator_id"`
	TargetUserID       pgtype.UUID     `json:"target_user_id"`
	TargetCredentialID pgtype.UUID     `json:"target_credential_id"`
	Detail             json.RawMessage `json:"detail"`
	CreatedAt          time.Time       `json:"created_at"`
}

type ConsoleBillingRecord struct {
	ID                    uuid.UUID   `json:"id"`
	IntegratorID          uuid.UUID   `json:"integrator_id"`
	Environment           string      `json:"environment"`
	Period                string      `json:"period"`
	AccountsProvisioned   int64       `json:"accounts_provisioned"`
	TransactionsProcessed int64       `json:"transactions_processed"`
	WebhookDeliveries     int64       `json:"webhook_deliveries"`
	AmountDueKobo         int64       `json:"amount_due_kobo"`
	AdjustmentKobo        int64       `json:"adjustment_kobo"`
	AdjustmentReason      pgtype.Text `json:"adjustment_reason"`
	SyncedAt              time.Time   `json:"synced_at"`
}

type ConsoleEmailVerificationToken struct {
	ID        string             `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type ConsoleInvitation struct {
	ID           string             `json:"id"`
	IntegratorID uuid.UUID          `json:"integrator_id"`
	InvitedBy    uuid.UUID          `json:"invited_by"`
	Email        string             `json:"email"`
	Role         interface{}        `json:"role"`
	ExpiresAt    time.Time          `json:"expires_at"`
	AcceptedAt   pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type ConsoleInvoice struct {
	ID              uuid.UUID          `json:"id"`
	IntegratorID    uuid.UUID          `json:"integrator_id"`
	BillingRecordID uuid.UUID          `json:"billing_record_id"`
	Period          string             `json:"period"`
	AmountKobo      int64              `json:"amount_kobo"`
	Status          string             `json:"status"`
	NombaOrderRef   pgtype.Text        `json:"nomba_order_ref"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	RetryCount      int32              `json:"retry_count"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type ConsolePasswordResetToken struct {
	ID        string             `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type ConsolePaymentMethod struct {
	ID            uuid.UUID   `json:"id"`
	IntegratorID  uuid.UUID   `json:"integrator_id"`
	NombaTokenKey string      `json:"nomba_token_key"`
	CardLast4     pgtype.Text `json:"card_last4"`
	CardBrand     pgtype.Text `json:"card_brand"`
	IsDefault     bool        `json:"is_default"`
	CreatedAt     time.Time   `json:"created_at"`
}

type ConsolePayout struct {
	ID                    uuid.UUID   `json:"id"`
	IntegratorID          uuid.UUID   `json:"integrator_id"`
	BankAccountID         uuid.UUID   `json:"bank_account_id"`
	RequestedAmountKobo   int64       `json:"requested_amount_kobo"`
	PlatformFeeKobo       int64       `json:"platform_fee_kobo"`
	TransferFeeBufferKobo int64       `json:"transfer_fee_buffer_kobo"`
	ActualTransferFeeKobo pgtype.Int8 `json:"actual_transfer_fee_kobo"`
	NetAmountKobo         int64       `json:"net_amount_kobo"`
	Status                string      `json:"status"`
	FailureReason         pgtype.Text `json:"failure_reason"`
	MerchantTxRef         string      `json:"merchant_tx_ref"`
	NombaTransferID       pgtype.Text `json:"nomba_transfer_id"`
	InitiatedBy           uuid.UUID   `json:"initiated_by"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type ConsolePayoutBankAccount struct {
	ID            uuid.UUID `json:"id"`
	IntegratorID  uuid.UUID `json:"integrator_id"`
	AccountNumber string    `json:"account_number"`
	AccountName   string    `json:"account_name"`
	BankCode      string    `json:"bank_code"`
	BankName      string    `json:"bank_name"`
	IsActive      bool      `json:"is_active"`
	CreatedBy     uuid.UUID `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ConsoleSession struct {
	ID        string             `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt time.Time          `json:"expires_at"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type ConsoleUsageEvent struct {
	ID           uuid.UUID `json:"id"`
	IntegratorID uuid.UUID `json:"integrator_id"`
	Environment  string    `json:"environment"`
	EventType    string    `json:"event_type"`
	ReferenceID  string    `json:"reference_id"`
	AmountKobo   int64     `json:"amount_kobo"`
	OccurredAt   time.Time `json:"occurred_at"`
}

type ConsoleUser struct {
	ID              uuid.UUID          `json:"id"`
	IntegratorID    pgtype.UUID        `json:"integrator_id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            interface{}        `json:"role"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type ConsoleWebhook struct {
	ID           uuid.UUID       `json:"id"`
	IntegratorID uuid.UUID       `json:"integrator_id"`
	Environment  string          `json:"environment"`
	Url          string          `json:"url"`
	Secret       string          `json:"secret"`
	Status       interface{}     `json:"status"`
	Events       json.RawMessage `json:"events"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Exception struct {
	ID                  uuid.UUID          `json:"id"`
	IntegratorID        uuid.UUID          `json:"integrator_id"`
	Type                string             `json:"type"`
	AmountKobo          int64              `json:"amount_kobo"`
	NombaReference      string             `json:"nomba_reference"`
	RelatedAccountID    pgtype.UUID        `json:"related_account_id"`
	Status              string             `json:"status"`
	ResolutionAction    pgtype.Text        `json:"resolution_action"`
	ResolutionNotes     pgtype.Text        `json:"resolution_notes"`
	SuccessorIdentityID pgtype.UUID        `json:"successor_identity_id"`
	DetectedAt          time.Time          `json:"detected_at"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt           time.Time          `json:"created_at"`
}

type IdempotencyKey struct {
	NombaReference string    `json:"nomba_reference"`
	LedgerEntryID  uuid.UUID `json:"ledger_entry_id"`
	FirstSeenVia   string    `json:"first_seen_via"`
	CreatedAt      time.Time `json:"created_at"`
}

type Identity struct {
	ID                uuid.UUID       `json:"id"`
	IntegratorID      uuid.UUID       `json:"integrator_id"`
	ExternalReference string          `json:"external_reference"`
	DisplayName       string          `json:"display_name"`
	State             string          `json:"state"`
	FailureReason     pgtype.Text     `json:"failure_reason"`
	Metadata          json.RawMessage `json:"metadata"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type IdentityEvent struct {
	ID            uuid.UUID       `json:"id"`
	IdentityID    uuid.UUID       `json:"identity_id"`
	EventType     string          `json:"event_type"`
	PreviousState pgtype.Text     `json:"previous_state"`
	NewState      pgtype.Text     `json:"new_state"`
	Detail        json.RawMessage `json:"detail"`
	CreatedAt     time.Time       `json:"created_at"`
}

type LedgerEntry struct {
	ID               uuid.UUID   `json:"id"`
	VirtualAccountID uuid.UUID   `json:"virtual_account_id"`
	IdentityID       uuid.UUID   `json:"identity_id"`
	AmountKobo       int64       `json:"amount_kobo"`
	Direction        string      `json:"direction"`
	Status           string      `json:"status"`
	NombaReference   string      `json:"nomba_reference"`
	Source           string      `json:"source"`
	Narration        pgtype.Text `json:"narration"`
	SenderName       pgtype.Text `json:"sender_name"`
	OccurredAt       time.Time   `json:"occurred_at"`
	CreatedAt        time.Time   `json:"created_at"`
}

type RequestLog struct {
	ID           uuid.UUID `json:"id"`
	IntegratorID uuid.UUID `json:"integrator_id"`
	Method       string    `json:"method"`
	Path         string    `json:"path"`
	StatusCode   int32     `json:"status_code"`
	LatencyMs    int32     `json:"latency_ms"`
	RequestID    string    `json:"request_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type VirtualAccount struct {
	ID                 uuid.UUID   `json:"id"`
	IdentityID         uuid.UUID   `json:"identity_id"`
	NombaAccountRef    string      `json:"nomba_account_ref"`
	AccountNumber      pgtype.Text `json:"account_number"`
	BankName           pgtype.Text `json:"bank_name"`
	AccountName        pgtype.Text `json:"account_name"`
	IsActive           bool        `json:"is_active"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
	ExpectedAmountKobo pgtype.Int8 `json:"expected_amount_kobo"`
	IsExpired          bool        `json:"is_expired"`
}
