// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiIntegrator struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	ApiKey        string    `json:"api_key"`
	ApiSecretHash string    `json:"api_secret_hash"`
	IsSandbox     bool      `json:"is_sandbox"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Exception struct {
	ID                  uuid.UUID          `json:"id"`
	IntegratorID        uuid.UUID          `json:"integrator_id"`
	Type                string             `json:"type"`
	AmountKobo          int64              `json:"amount_kobo"`
	NombaReference      string             `json:"nomba_reference"`
	RelatedAccountID    pgtype.UUID        `json:"related_account_id"`
	Status              string             `json:"status"`
	ResolutionAction    pgtype.Text        `json:"resolution_action"`
	ResolutionNotes     pgtype.Text        `json:"resolution_notes"`
	SuccessorIdentityID pgtype.UUID        `json:"successor_identity_id"`
	DetectedAt          time.Time          `json:"detected_at"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt           time.Time          `json:"created_at"`
}

type IdempotencyKey struct {
	NombaReference string    `json:"nomba_reference"`
	LedgerEntryID  uuid.UUID `json:"ledger_entry_id"`
	FirstSeenVia   string    `json:"first_seen_via"`
	CreatedAt      time.Time `json:"created_at"`
}

type Identity struct {
	ID                uuid.UUID       `json:"id"`
	IntegratorID      uuid.UUID       `json:"integrator_id"`
	ExternalReference string          `json:"external_reference"`
	DisplayName       string          `json:"display_name"`
	KycTier           string          `json:"kyc_tier"`
	State             string          `json:"state"`
	FailureReason     pgtype.Text     `json:"failure_reason"`
	Metadata          json.RawMessage `json:"metadata"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type IdentityEvent struct {
	ID            uuid.UUID       `json:"id"`
	IdentityID    uuid.UUID       `json:"identity_id"`
	EventType     string          `json:"event_type"`
	PreviousState pgtype.Text     `json:"previous_state"`
	NewState      pgtype.Text     `json:"new_state"`
	Detail        json.RawMessage `json:"detail"`
	CreatedAt     time.Time       `json:"created_at"`
}

type LedgerEntry struct {
	ID               uuid.UUID   `json:"id"`
	VirtualAccountID uuid.UUID   `json:"virtual_account_id"`
	IdentityID       uuid.UUID   `json:"identity_id"`
	AmountKobo       int64       `json:"amount_kobo"`
	Direction        string      `json:"direction"`
	Status           string      `json:"status"`
	NombaReference   string      `json:"nomba_reference"`
	Source           string      `json:"source"`
	Narration        pgtype.Text `json:"narration"`
	SenderName       pgtype.Text `json:"sender_name"`
	OccurredAt       time.Time   `json:"occurred_at"`
	CreatedAt        time.Time   `json:"created_at"`
}

type VirtualAccount struct {
	ID              uuid.UUID   `json:"id"`
	IdentityID      uuid.UUID   `json:"identity_id"`
	NombaAccountRef string      `json:"nomba_account_ref"`
	AccountNumber   pgtype.Text `json:"account_number"`
	BankName        pgtype.Text `json:"bank_name"`
	AccountName     pgtype.Text `json:"account_name"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}
