// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInProgressPayouts = `-- name: CountInProgressPayouts :one
SELECT COUNT(*) FROM console.payouts
WHERE integrator_id = $1 AND status IN ('pending', 'processing')
`

// Returns the number of payouts currently in 'pending' or 'processing' state.
// Used to prevent an integrator from initiating a second concurrent payout.
func (q *Queries) CountInProgressPayouts(ctx context.Context, integratorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInProgressPayouts, integratorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayout = `-- name: CreatePayout :one

INSERT INTO console.payouts (
    integrator_id,
    bank_account_id,
    requested_amount_kobo,
    platform_fee_kobo,
    transfer_fee_buffer_kobo,
    net_amount_kobo,
    merchant_tx_ref,
    initiated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, integrator_id, bank_account_id, requested_amount_kobo, platform_fee_kobo, transfer_fee_buffer_kobo, actual_transfer_fee_kobo, net_amount_kobo, status, failure_reason, merchant_tx_ref, nomba_transfer_id, initiated_by, created_at, updated_at
`

type CreatePayoutParams struct {
	IntegratorID          uuid.UUID `json:"integrator_id"`
	BankAccountID         uuid.UUID `json:"bank_account_id"`
	RequestedAmountKobo   int64     `json:"requested_amount_kobo"`
	PlatformFeeKobo       int64     `json:"platform_fee_kobo"`
	TransferFeeBufferKobo int64     `json:"transfer_fee_buffer_kobo"`
	NetAmountKobo         int64     `json:"net_amount_kobo"`
	MerchantTxRef         string    `json:"merchant_tx_ref"`
	InitiatedBy           uuid.UUID `json:"initiated_by"`
}

// ---------------------------------------------------------------------------
// Payout lifecycle
// ---------------------------------------------------------------------------
func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (ConsolePayout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.IntegratorID,
		arg.BankAccountID,
		arg.RequestedAmountKobo,
		arg.PlatformFeeKobo,
		arg.TransferFeeBufferKobo,
		arg.NetAmountKobo,
		arg.MerchantTxRef,
		arg.InitiatedBy,
	)
	var i ConsolePayout
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.BankAccountID,
		&i.RequestedAmountKobo,
		&i.PlatformFeeKobo,
		&i.TransferFeeBufferKobo,
		&i.ActualTransferFeeKobo,
		&i.NetAmountKobo,
		&i.Status,
		&i.FailureReason,
		&i.MerchantTxRef,
		&i.NombaTransferID,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditIntegratorBalance = `-- name: CreditIntegratorBalance :exec
UPDATE public.api_integrators
SET
    wallet_balance_kobo = wallet_balance_kobo + $2,
    updated_at          = now()
WHERE id = $1
`

type CreditIntegratorBalanceParams struct {
	ID                uuid.UUID `json:"id"`
	WalletBalanceKobo int64     `json:"wallet_balance_kobo"`
}

// Reversal: re-credits the balance when a payout fails after deduction.
// Also used by the webhook handler to reverse a failed transfer.
func (q *Queries) CreditIntegratorBalance(ctx context.Context, arg CreditIntegratorBalanceParams) error {
	_, err := q.db.Exec(ctx, creditIntegratorBalance, arg.ID, arg.WalletBalanceKobo)
	return err
}

const deactivatePayoutBankAccounts = `-- name: DeactivatePayoutBankAccounts :exec
UPDATE console.payout_bank_accounts
SET is_active = FALSE, updated_at = now()
WHERE integrator_id = $1 AND is_active = TRUE
`

// Marks all active bank accounts for an integrator as inactive.
// Always called inside a transaction before InsertPayoutBankAccount.
func (q *Queries) DeactivatePayoutBankAccounts(ctx context.Context, integratorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivatePayoutBankAccounts, integratorID)
	return err
}

const deductIntegratorBalance = `-- name: DeductIntegratorBalance :one
UPDATE public.api_integrators
SET
    wallet_balance_kobo = wallet_balance_kobo - $2,
    updated_at          = now()
WHERE id = $1
  AND wallet_balance_kobo >= $2
RETURNING wallet_balance_kobo
`

type DeductIntegratorBalanceParams struct {
	ID                uuid.UUID `json:"id"`
	WalletBalanceKobo int64     `json:"wallet_balance_kobo"`
}

// Atomically deducts the given amount from wallet_balance_kobo.
// The WHERE clause ensures we never go negative: if balance < amount,
// zero rows are updated and the caller must roll back.
func (q *Queries) DeductIntegratorBalance(ctx context.Context, arg DeductIntegratorBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, deductIntegratorBalance, arg.ID, arg.WalletBalanceKobo)
	var wallet_balance_kobo int64
	err := row.Scan(&wallet_balance_kobo)
	return wallet_balance_kobo, err
}

const getActivePayoutBankAccount = `-- name: GetActivePayoutBankAccount :one


SELECT id, integrator_id, account_number, account_name, bank_code, bank_name, is_active, created_by, created_at, updated_at FROM console.payout_bank_accounts
WHERE integrator_id = $1 AND is_active = TRUE
LIMIT 1
`

// internal/platform/db/queries/payouts.sql
// SQLC queries for the payout system.
// All tables live in the console schema. Balance lives on public.api_integrators.
// ---------------------------------------------------------------------------
// Bank account management
// ---------------------------------------------------------------------------
func (q *Queries) GetActivePayoutBankAccount(ctx context.Context, integratorID uuid.UUID) (ConsolePayoutBankAccount, error) {
	row := q.db.QueryRow(ctx, getActivePayoutBankAccount, integratorID)
	var i ConsolePayoutBankAccount
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.AccountNumber,
		&i.AccountName,
		&i.BankCode,
		&i.BankName,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, integrator_id, bank_account_id, requested_amount_kobo, platform_fee_kobo, transfer_fee_buffer_kobo, actual_transfer_fee_kobo, net_amount_kobo, status, failure_reason, merchant_tx_ref, nomba_transfer_id, initiated_by, created_at, updated_at FROM console.payouts
WHERE id = $1
`

func (q *Queries) GetPayoutByID(ctx context.Context, id uuid.UUID) (ConsolePayout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	var i ConsolePayout
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.BankAccountID,
		&i.RequestedAmountKobo,
		&i.PlatformFeeKobo,
		&i.TransferFeeBufferKobo,
		&i.ActualTransferFeeKobo,
		&i.NetAmountKobo,
		&i.Status,
		&i.FailureReason,
		&i.MerchantTxRef,
		&i.NombaTransferID,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutByMerchantTxRef = `-- name: GetPayoutByMerchantTxRef :one
SELECT id, integrator_id, bank_account_id, requested_amount_kobo, platform_fee_kobo, transfer_fee_buffer_kobo, actual_transfer_fee_kobo, net_amount_kobo, status, failure_reason, merchant_tx_ref, nomba_transfer_id, initiated_by, created_at, updated_at FROM console.payouts
WHERE merchant_tx_ref = $1
`

func (q *Queries) GetPayoutByMerchantTxRef(ctx context.Context, merchantTxRef string) (ConsolePayout, error) {
	row := q.db.QueryRow(ctx, getPayoutByMerchantTxRef, merchantTxRef)
	var i ConsolePayout
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.BankAccountID,
		&i.RequestedAmountKobo,
		&i.PlatformFeeKobo,
		&i.TransferFeeBufferKobo,
		&i.ActualTransferFeeKobo,
		&i.NetAmountKobo,
		&i.Status,
		&i.FailureReason,
		&i.MerchantTxRef,
		&i.NombaTransferID,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayoutBankAccount = `-- name: InsertPayoutBankAccount :one
INSERT INTO console.payout_bank_accounts (
    integrator_id, account_number, account_name, bank_code, bank_name, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, integrator_id, account_number, account_name, bank_code, bank_name, is_active, created_by, created_at, updated_at
`

type InsertPayoutBankAccountParams struct {
	IntegratorID  uuid.UUID `json:"integrator_id"`
	AccountNumber string    `json:"account_number"`
	AccountName   string    `json:"account_name"`
	BankCode      string    `json:"bank_code"`
	BankName      string    `json:"bank_name"`
	CreatedBy     uuid.UUID `json:"created_by"`
}

func (q *Queries) InsertPayoutBankAccount(ctx context.Context, arg InsertPayoutBankAccountParams) (ConsolePayoutBankAccount, error) {
	row := q.db.QueryRow(ctx, insertPayoutBankAccount,
		arg.IntegratorID,
		arg.AccountNumber,
		arg.AccountName,
		arg.BankCode,
		arg.BankName,
		arg.CreatedBy,
	)
	var i ConsolePayoutBankAccount
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.AccountNumber,
		&i.AccountName,
		&i.BankCode,
		&i.BankName,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayoutsForIntegrator = `-- name: ListPayoutsForIntegrator :many
SELECT id, integrator_id, bank_account_id, requested_amount_kobo, platform_fee_kobo, transfer_fee_buffer_kobo, actual_transfer_fee_kobo, net_amount_kobo, status, failure_reason, merchant_tx_ref, nomba_transfer_id, initiated_by, created_at, updated_at FROM console.payouts
WHERE integrator_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPayoutsForIntegratorParams struct {
	IntegratorID uuid.UUID `json:"integrator_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListPayoutsForIntegrator(ctx context.Context, arg ListPayoutsForIntegratorParams) ([]ConsolePayout, error) {
	rows, err := q.db.Query(ctx, listPayoutsForIntegrator, arg.IntegratorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsolePayout{}
	for rows.Next() {
		var i ConsolePayout
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorID,
			&i.BankAccountID,
			&i.RequestedAmountKobo,
			&i.PlatformFeeKobo,
			&i.TransferFeeBufferKobo,
			&i.ActualTransferFeeKobo,
			&i.NetAmountKobo,
			&i.Status,
			&i.FailureReason,
			&i.MerchantTxRef,
			&i.NombaTransferID,
			&i.InitiatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIntegratorRow = `-- name: LockIntegratorRow :one

SELECT wallet_balance_kobo FROM public.api_integrators
WHERE id = $1
FOR UPDATE
`

// ---------------------------------------------------------------------------
// Balance operations on public.api_integrators
// These supplement the existing UpdateIntegratorWalletBalance query in billing.sql.
// ---------------------------------------------------------------------------
// Acquires a row-level lock on the integrator for the duration of the caller's
// transaction. MUST be called inside BEGIN/COMMIT. This prevents concurrent
// payout requests from racing to deduct the same balance.
func (q *Queries) LockIntegratorRow(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lockIntegratorRow, id)
	var wallet_balance_kobo int64
	err := row.Scan(&wallet_balance_kobo)
	return wallet_balance_kobo, err
}

const updatePayoutStatus = `-- name: UpdatePayoutStatus :one
UPDATE console.payouts
SET
    status                   = $2,
    failure_reason           = $3,
    nomba_transfer_id        = $4,
    actual_transfer_fee_kobo = $5,
    updated_at               = now()
WHERE id = $1
RETURNING id, integrator_id, bank_account_id, requested_amount_kobo, platform_fee_kobo, transfer_fee_buffer_kobo, actual_transfer_fee_kobo, net_amount_kobo, status, failure_reason, merchant_tx_ref, nomba_transfer_id, initiated_by, created_at, updated_at
`

type UpdatePayoutStatusParams struct {
	ID                    uuid.UUID   `json:"id"`
	Status                string      `json:"status"`
	FailureReason         pgtype.Text `json:"failure_reason"`
	NombaTransferID       pgtype.Text `json:"nomba_transfer_id"`
	ActualTransferFeeKobo pgtype.Int8 `json:"actual_transfer_fee_kobo"`
}

func (q *Queries) UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (ConsolePayout, error) {
	row := q.db.QueryRow(ctx, updatePayoutStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.NombaTransferID,
		arg.ActualTransferFeeKobo,
	)
	var i ConsolePayout
	err := row.Scan(
		&i.ID,
		&i.IntegratorID,
		&i.BankAccountID,
		&i.RequestedAmountKobo,
		&i.PlatformFeeKobo,
		&i.TransferFeeBufferKobo,
		&i.ActualTransferFeeKobo,
		&i.NetAmountKobo,
		&i.Status,
		&i.FailureReason,
		&i.MerchantTxRef,
		&i.NombaTransferID,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
