// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateApiCredential(ctx context.Context, arg CreateApiCredentialParams) (ApiCredential, error)
	CreateApiIntegrator(ctx context.Context, arg CreateApiIntegratorParams) (ApiIntegrator, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	CreateVirtualAccount(ctx context.Context, arg CreateVirtualAccountParams) (VirtualAccount, error)
	// Sets is_active to false when a new account is provisioned for the identity
	DeactivateVirtualAccount(ctx context.Context, identityID uuid.UUID) error
	GetActiveVirtualAccountByIdentityID(ctx context.Context, identityID uuid.UUID) (VirtualAccount, error)
	GetApiIntegratorByKey(ctx context.Context, keyID string) (GetApiIntegratorByKeyRow, error)
	GetExceptionByID(ctx context.Context, arg GetExceptionByIDParams) (Exception, error)
	GetIdempotencyKey(ctx context.Context, nombaReference string) (IdempotencyKey, error)
	GetIdentityByExternalReference(ctx context.Context, arg GetIdentityByExternalReferenceParams) (Identity, error)
	GetIdentityByID(ctx context.Context, arg GetIdentityByIDParams) (Identity, error)
	// Calculates the sum of all 'inbound' matched transactions before the given time
	GetLedgerOpeningBalance(ctx context.Context, arg GetLedgerOpeningBalanceParams) (int64, error)
	GetVirtualAccountByAccountNumber(ctx context.Context, accountNumber pgtype.Text) (VirtualAccount, error)
	GetVirtualAccountByID(ctx context.Context, id uuid.UUID) (VirtualAccount, error)
	InsertException(ctx context.Context, arg InsertExceptionParams) (Exception, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error)
	InsertIdentityEvent(ctx context.Context, arg InsertIdentityEventParams) (IdentityEvent, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	ListActiveVirtualAccounts(ctx context.Context) ([]VirtualAccount, error)
	ListAllIdentitiesByState(ctx context.Context, state string) ([]Identity, error)
	ListExceptionsByStatus(ctx context.Context, arg ListExceptionsByStatusParams) ([]Exception, error)
	ListIdentitiesByState(ctx context.Context, arg ListIdentitiesByStateParams) ([]Identity, error)
	ListIdentityEvents(ctx context.Context, identityID uuid.UUID) ([]IdentityEvent, error)
	ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error)
	ListLedgerEntriesByIdentityAndPeriod(ctx context.Context, arg ListLedgerEntriesByIdentityAndPeriodParams) ([]LedgerEntry, error)
	ListOpenExceptions(ctx context.Context, arg ListOpenExceptionsParams) ([]Exception, error)
	ResolveException(ctx context.Context, arg ResolveExceptionParams) (Exception, error)
	// Used for renames and metadata updates only. Never changes state or id.
	UpdateIdentityProfile(ctx context.Context, arg UpdateIdentityProfileParams) (Identity, error)
	// The only query allowed to mutate `state`. Called exclusively from
	// account/lifecycle.go's Transition() function, never directly from a handler
	// or service method, per the package boundary rules in ARCHITECTURE.md.
	UpdateIdentityState(ctx context.Context, arg UpdateIdentityStateParams) (Identity, error)
	// Called after a successful provisioning to set the account number and bank info
	UpdateVirtualAccountProvisioning(ctx context.Context, arg UpdateVirtualAccountProvisioningParams) (VirtualAccount, error)
}

var _ Querier = (*Queries)(nil)
